export default {
  WIN_CONDITION_EXACT: 'WIN_CONDITION_EXACT',
  WIN_CONDITION_HIGHER: 'WIN_CONDITION_HIGHER',

  PENALTY_RESET: 'PENALTY_RESET',
  PENALTY_EXCESS: 'PENALTY_EXCESS',
  PENALTY_SUBSTRACT: 'PENALTY_SUBSTRACT',

  SANCTION_ELIMINATED: 'SANCTION_ELIMINATED',
  SANCTION_RESET: 'SANCTION_RESET',
  SANCTION_NOTHING: 'SANCTION_NOTHING',

  ZAP_HALF: 'ZAP_HALF',
  ZAP_RESET: 'ZAP_RESET',
  ZAP_NOTHING: 'ZAP_NOTHING',
};
